---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: hello-world
  metadata:
    labels:
      global-balancer: hello-world
spec:
  to:
    kind: Service
    name: hello-world
    weight: 100
  port:
    targetPort: 8080
  tls:
    termination: edge
  wildcardPolicy: None
